# Generated by Django 4.0.3 on 2022-03-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='like',
        ),
    ]
