# Generated by Django 4.0.3 on 2022-03-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_likes_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
